# Use the README file as a reference to customize settings.

EntretResult:
  fields:
    default: day, entry, retire, entret, entry_total, retire_total, active_total
    form: day, entry, retire, entret, entry_total, retire_total, active_total
  relationships: 
  application: Application
