# Use the README file as a reference to customize settings.

RecipeComment:
  fields:
    default: recipe_id, user_id, content, image
    form: recipe_id, user_id, content, image
  relationships: 
  application: Application
