# Use the README file as a reference to customize settings.

Recipe:
  fields:
    default: user_id, title, description, one_point, status
    form: user_id, title, description, one_point, status
  relationships: recipe_steps, recipe_foodstuffs
  application: Application
