# Use the README file as a reference to customize settings.

RecommendRecipeMail:
  fields:
    default: day, recipe_id, news_text
    form: day, recipe_id, news_text
  relationships: 
  application: Application
