# Use the README file as a reference to customize settings.

RestaurantComment:
  fields:
    default: restaurant_id, user_id, comment, public, point
    form: restaurant_id, user_id, comment, public, point
  relationships: 
  application: Application
