# Use the README file as a reference to customize settings.

UserProfileVisibility:
  fields:
    default: user_profile_id, nickname, sex, first_name, family_name, email, birthday, postcode, address
    form: user_profile_id, nickname, sex, first_name, family_name, email, birthday, postcode, address
  relationships: 
  application: Application
