# Use the README file as a reference to customize settings.

UserInfo:
  fields:
    default: user_id, nickname, sex, first_name, last_name, birthday, mail_address, postcode, address, address_point
    form: user_id, nickname, sex, first_name, last_name, birthday, mail_address, postcode, address, address_point
  relationships: 
  application: Application
