# Use the README file as a reference to customize settings.

UserProfile:
  fields:
    default: user_id, nickname, sex, first_name, family_name, birthday, email, prefecture_id, prefecture_id, recipe_count
    form: user_id, nickname, sex, first_name, family_name, birthday, email, prefecture_id, prefecture_id, comment
  relationships: 
  application: Application
