development:
  adapter: mysql2
  database: cook24_dev 
  username: root
  password: root
  host: localhost

test:
  adapter: mysql2
  database: cook24_test
  username: root
  password: root
  host: localhost

staging:
  adapter: mysql2
  database: cook24_staging
  username: root
  host: localhost

production:
  adapter: mysql2
  database: cook24_main
  username: cook24
  host: localhost

cook24_users:
  adapter: mysql2
  database: cook24_users 
  username: root
  host: localhost

