development:
  adapter: mysql2
  database: ras_vn_dev 
  username: root
  host: localhost

test:
  adapter: mysql2
  database: ras_vn_test
  username: root
  thost: localhost

staging:
  adapter: mysql2
  database: ras_vn_staging
  username: root
  thost: localhost

production:
  adapter: mysql2
  database: ras_vn
  username: root
  thost: localhost

ras_vn_users:
  adapter: mysql2
  database: ras_vn_users 
  username: root
  host: localhost

